name: Deploy to Azure VM via Docker Compose

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # Setup SSH step hata diya gaya hai.
      
      - name: Deploy Docker Containers on Azure VM
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          # âœ… Yahi woh line hai jo add karni thi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            cd ~/Final-lab
            git pull
            docker-compose down 
            docker-compose up --build -d
            docker logs todo_backend
